# Generated by Django 4.1.10 on 2024-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в Telegram'),
        ),
        migrations.AddField(
            model_name='partners',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в Telegram'),
        ),
    ]
