# Generated by Django 4.1.10 on 2024-03-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_operators_telegram_id_partners_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.operators', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'График',
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
