# Generated by Django 4.1.10 on 2024-05-01 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_clients_callback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Доп. номер телефона'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Доп. номер телефона'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='call_result',
            field=models.CharField(choices=[('AG', 'Заявка'), ('NO', 'Отказ'), ('PR', 'Думает'), ('NA', 'Недозвон'), ('NEW', 'Новый клиент'), ('NAF', 'Отказ по недозвону')], default='NEW', max_length=3, verbose_name='Результат звонка'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='callback_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата повторного звонка'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='client_info',
            field=models.TextField(blank=True, verbose_name='Данные для заявки (дата рождения, паспорт...)'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('DIS', 'Согласование визита'), ('FIX', 'Назначен визит'), ('VRF', 'Подключен - проверка оплаты'), ('FIN', 'Подключен - абон.плата внесена'), ('FAIL', 'Отказ'), ('NAF', 'Отказ по недозвону')], max_length=4, null=True, verbose_name='Статус подключения'),
        ),
    ]
